platform :ios, '9.0'

target 'kipp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  # https://github.com/facebook/react-native/blob/v0.59.4/React.podspec
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTImage',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'FBSDKCoreKit', '~> 4.42.0'
  pod 'FBSDKLoginKit', '~> 4.42.0'
  pod 'FBSDKShareKit', '~> 4.42.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

